### ISSUE TITLE
 CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by lijain** [jozhang97/DETA#1]
Thanks for the project you shared, but I have this problem during distributed training, can you bother to guide?
![image](https://user-images.githubusercontent.com/18046568/208072498-03346e42-79bd-4cd0-9a5e-184e9a33f26c.png)

**Comment by jozhang97** [comment]
Hi, Thanks for trying out the code, sorry to hear you are having some issues.
Can you provide some additional information? What command did you run? CUDA version? torch version?

**Comment by lijain** [comment]
Hello, my torch 11.2 with the corresponding cuda, in addition run the command no problem, is the piece of data out of bounds??

**Comment by jozhang97** [comment]
Hi, Unfortunately with the current information I am given, it is very hard for me to understand what is going on and how to help you.

Can you provide some additional information? What command did you run? CUDA version?

What happens if you `git clone https://github.com/fundamentalvision/Deformable-DETR.git` and run `GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/r50_deformable_detr.sh` with the same conda environment?

I ran `GPUS_PER_NODE=8 ./tools/run_dist_launch.sh 8 ./configs/deta.sh --coco_path ./data/coco` on my machine just now and it works fine.
